### ISSUE TITLE
Evmos + Fetch not compitable

### ISSUE THREAD

**Issue by Femkecl** [QuokkaStake/cosmos-validators-exporter#2]
goroutine 83 [running]:
cosmossdk.io/math.Int.Int64({0xc000236600?})
        /home/runner/go/pkg/mod/cosmossdk.io/math@v1.0.0-beta.2/int.go:158 +0x86
main.(*RPC).GetSingleDelegation(0xc000236600, {0xc000fda880, 0x33}, {0xc000e26090, 0x2c})
        /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/tendermint.go:76 +0x18c
main.(*Manager).GetSelfDelegationsBalance(0xc0010dc6e0, {{0xc000fbf938, 0x5}, {0xc000e6cff0, 0x21}, {0xc000fbf960, 0x5}, {0xc000fbf968, 0x5}, 0xf4240, ...}, ...)
        /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/manager.go:297 +0x159
main.(*Manager).GetAllValidators.func1.4()
        /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/manager.go:116 +0x9d
created by main.(*Manager).GetAllValidators.func1
        /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/manager.go:115 +0x993
cosmos-validators-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
cosmos-validators-exporter.service: Failed with result 'exit-code'.
cosmos-validators-exporter.service: Scheduled restart job, restart counter is at 2.
Stopped Cosmos Validators Exporter.
Started Cosmos Validators Exporter.

**Comment by freak12techno** [comment]
@Femkecl just pushed v1.4.1, can you check if the issue is still present there and close it if so?

**Comment by Femkecl** [comment]
This fixes it!
