### ISSUE TITLE
Dexscreener only price source for asset

### ISSUE THREAD

**Issue by jcdmacleod** [QuokkaStake/cosmos-validators-exporter#40]
We tried to use this against our Provenance config, but Provenance was removed from coingecko, so the API returns "{}" for that asset.  I presumed that the price would then be taken from dexscreener but it appears as though it doesn't fail as I expected.

Config:

[[chains]]
name = "Provenance"
lcd-endpoint = "https://api.provenance.io"
base-denom = "nhash"
denoms = [
 { denom = "nhash", display-denom = "hash", coingecko-currency = "provenance", denom-coefficient = 10000000000, dex-screener-chain-id = "osmosis", dex-screener-pair-id = "693" },
]
bech-wallet-prefix = "pb"
validators = [
 { address = "pbvaloper1xnjupruwluzml987cljf225hyxfnzt6lnmacgv", consensus-address = "pbvalcons1thsssqk5lguk5295faxc9lstywg6ek5satchqm" }
]
[chains.queries]
validator = true
delegations = true
unbonds = true
self-delegation = true
validators = true
commission = true
rewards = true
balance = true
signing-info = true
slashing-params = true
staking-params = true

**Comment by freak12techno** [comment]
@jcdmacleod I just checked, it seems like the misleading config example here. The param should be named `dex-screener-pair `, not `dex-screener-pair-id`.

I fixed the docs there https://github.com/QuokkaStake/cosmos-validators-exporter/pull/41, so no code changes are needed, can you verify that updating the config to specify the correct value would work correctly? I will merge it once you confirm, seems to work for me, but better to confirm if it'll also work for you.

Thanks for pointing that out!
