### ISSUE TITLE
What is LCD endpoint

### ISSUE THREAD

**Issue by thenhthang** [QuokkaStake/cosmos-validators-exporter#76]
# LCD endpoint to query data from. Required.
lcd-endpoint = "https://api.cosmos.quokkastake.io"

How to get my own LCD endpoint, is it IP:8545?

**Comment by freak12techno** [comment]
@thenhthang usually for cosmos-sdk chains it's defined in app.toml this way:
```
[api]

# Enable defines if the API server should be enabled.
enable = true

# Swagger defines if swagger documentation should automatically be registered.
swagger = true

# Address defines the API server to listen on.
address = "tcp://0.0.0.0:1317"
```
so you have to enable it on your node (as it's disabled by default) and expose it. The default port is 1317, but you can also put it behind a reverse proxy (that's what I am doing).

Does this answer your question?
